config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :posts
  resources :comments
  get "/users/:user_id/posts", to: "posts#user_posts", as: 'user_post'
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 255, too_long: "Anda melebihi batas maksimal 255 karakter" }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates_associated :comments
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 255, too_long: "Anda melebihi batas maksimal 255 karakter" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy

  validates_associated :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]

  def create
    @comment = Comment.create(comments_params.merge(user_id: current_user.id))
    if @comment.valid?
      redirect_to post_path(@comment.post_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update 
    @comment = Comment.find(params[:id]);
    if @comment.update(comments_params)
      redirect_to post_path(@comment.post_id)
    end
  end

  def edit 
    @comment = Comment.find(params[:id])
  end

  def destroy 
    @comment = Comment.find(params[:id])
    if @comment.present?
      @comment.destroy
      redirect_to posts_path
    end
  end

  private

  def comments_params 
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]

  def index 
    @posts = Post.order("updated_at desc")
    @comment = Comment.new

    if !@posts.empty?
      respond('index', data: @posts)
    else
      respond('index', data: nil, status_code: :not_found)
    end

  end

  def show 
    @post = Post.find(params[:id])
    @comments = @post.comments.all
  end

  def new 
    @post = Post.new
  end

  def create 
    @post = Post.create(posts_params.merge(user_id: current_user.id))

    if @post.valid?
      flash[:notice] = "Berhasil menambahkan postingan"
      redirect_to posts_path
    else
      flash[:alert] = "Gagal menambahkan post baru"
      redirect_to new_post_url
    end

  end

  def update 
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      flash[:notice] = "Berhasil memperbarui postingan"
      redirect_to user_post_path(current_user.id)
    else
      flash[:alert] = "Gagal memperbarui postingan"
      redirect_to user_post_path(current_user.id)
    end
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def destroy 
    @post = current_user.posts.find(params[:id])
    if @post.present?
      @post.destroy
      flash[:notice] = "Berhasil menghapus postingan"
      redirect_to posts_path
    end
  end

  def user_posts 
    user = User.find(params[:user_id])
    @posts = user.posts.all.order("updated_at desc")
    
    if !@posts.empty?
      respond('user_posts', data: @posts)
    else
      respond('user_posts', data: nil, status_code: :not_found)
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :body)
  end

  def respond(path, data: [], **args)
    if args[:status_code]
      status_code = args[:status_code]
    end
    respond_to do | format |
      format.html { render path }
      format.json { render json: { data: data }, status: status_code }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h2 class="text-center font-bold text-2xl">Update Comment</h2>
<%= form_with model: @comment, url: "/comments/#{@comment.id}", class: "container mx-auto flex flex-col space-y-4",  method: :put do |form| %>
  <%= form.label :body, "Your comment :"%>
  <%= form.text_area :body, size: "60x10", class: "p-2 border border-violet-500 rounded-md", value: @comment.body %>
  <%= form.button "Update comment", class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.27.0/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'pages/header' %>
    <% flash.each do |message_type, message| %>
      <% case message_type %>
        <% when "notice" %>
          <div class="alert alert-success shadow-lg w-4/12 ml-2">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              <span><%= message  %></span>
            </div>
          </div>
        <% when "alert" %>
          <div class="alert alert-warning shadow-lg w-4/12 ml-2">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
              <span><%= message %></span>
            </div>
          </div>
        <% when "error" %>
          <div class="alert alert-error shadow-lg w-4/12 ml-2">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              <span><%= message %></span>
            </div>
          </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal p-0">
      <li>
        <%= link_to "Home", root_path%>
      </li>
      <li>
        <%= link_to "Post", posts_path%>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to "My Posts", user_post_path(current_user.id), method: :get %>
      </li>
      <% end %>
      <li tabindex="0">
        <a>
          Account
          <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
        </a>
        <ul class="p-2 bg-base-100">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path %>
            </li>
            <!-- <li>
              <%= link_to "My Posts", user_post_path(current_user.id), method: :get %>
            </li> -->
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>        
              <%= link_to "Sign In", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/posts/edit.html.erb
<h2 class="text-center font-bold text-2xl">Update Post</h2>
<%= form_with model: @post, url: "/posts/#{@post.id}", class: "container mx-auto flex flex-col space-y-4",  method: :put do |form| %>
  <%= form.label :title, "Title :"%>
  <%= form.text_field :title, class: "p-2 border border-violet-500 rounded-md", value: @post.title %>
  <%= form.label :body, "Your content :"%>
  <%= form.text_area :body, size: "60x10", class: "p-2 border border-violet-500 rounded-md", value: @post.body %>
  <%= form.button class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2"%>
<% end %>

app/views/posts/index.html.erb
<div class="container mx-auto mt-10  flex flex-col space-y-8">
  <% if user_signed_in? %>
    <%= link_to "Create new post", new_post_path, class: "btn btn-primary w-[200px]" %>
  <% end %>

  <h1 class="text-center font-bold text-2xl">All Posts</h1>
  <ul class="flex flex-col gap-y-4">
  <%  @posts.each do | post | %>
    <% p = Post.find(post.id) %>
    <% comment_count = p.comments.all.count %>
    <div class="card bg-base-100 shadow-xl w-8/12 mx-auto">
      <div class="card-body">
        <h2 class="card-title"><%= post.title %></h2>
        <p><%= post.body %></p>
        <% if user_signed_in? %>
          <%= form_with model: @comment, url: "/comments", class: "mt-8 flex items-center",  method: :post do |form| %>
            <%= form.hidden_field :post_id, value: post.id %>
            <%= form.text_field :body, class: "border border-violet-500 rounded-md w-full mr-2" %>
            <%= form.button "Reply", class: "bg-violet-800 text-white py-2 px-6 rounded-md"%>
          <% end %>
        <% end %>
        <div class="mt-2 text-sm text-end text-gray-400">
          <p>By: <%= post.user.email %></p>
          <p>Diposting pada: <%= post.created_at %></p>
        </div>
        <% if comment_count > 0 %>
          <%= link_to "Cek komentar(#{comment_count})", post_path(post.id), class: "text-violet-700 font-semibold" %>
        <% end %>
      </div>
    </div>
  <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<h2 class="text-center font-bold text-2xl">Create new Post</h2>
<!-- <form action="/posts" class="container mx-auto flex flex-col space-y-4" method="POST">
  <div class="flex flex-col">
    <label for="title">Title: </label>
    <input class="border border-violet-500 rounded-md" type="text" name="title" id="title">
  </div>
  <div class="flex flex-col">
    <label for="body">Your content: </label>
    <textarea class="p-2 border border-violet-500 rounded-md" name="body" id="body" cols="30" rows="10"></textarea>
  </div>
  <button class="bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2" type="submit">Post</button>
</form> -->
<%= form_with model: @post, url: "/posts", method: :post, class: "container mx-auto flex flex-col space-y-4" do |form| %>
  <%= form.label :title, "Title :"%>
  <%= form.text_field :title, class: "p-2 border border-violet-500 rounded-md" %>
  <%= form.label :body, "Your content :"%>
  <%= form.text_area :body, size: "60x10", class: "p-2 border border-violet-500 rounded-md" %>
  <%= form.button class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2"%>
<% end %>

app/views/posts/show.html.erb
<% p = Post.find(@post.id) %>
<% comment_count = p.comments.all.count %>

<div class="w-8/12 mx-auto">
  <div class="card bg-base-100 shadow-xl w-full mb-8">
    <div class="px-8 py-6">
      <h2 class="card-title"><%= @post.title %></h2>
      <p><%= @post.body %></p>
      <div class="mt-2 text-sm text-end text-gray-400">
        <p>By: <%= @post.user.email %></p>
        <p>Diposting pada: <%= @post.created_at %></p>
      </div>
    </div>
  </div>
  <div class="card-actions justify-start mt-8">
    <p class="text-violet-800">Daftar komentar</p>
  </div>
  <% if @comments.empty? %>
    <p class="mt-8">Belum ada komentar</p>
  <% else %>
  <div class="flex flex-col gap-y-4">
    <% @comments.each do | comment | %>
      <div class="card bg-base-100 shadow-xl w-full">
        <div class="card-body">
          <h2 class="card-title"><%= comment.user.email %></h2>
          <p><%= comment.body %></p>
          <div class="card-actions justify-between mt-8">
            <p class="text-gray-400"><%= comment.created_at %></p>
            <% if user_signed_in? && current_user.id == comment.user_id%>
              <div class="flex items-center space-x-2">
                <%= link_to "Update", edit_comment_path(comment), class: "text-violet-800 font-semibold" %>
                <%= form_with url: "/comments/#{comment.id}", method: :delete, data: { turbo_confirm: 'Delete comment?' } do |form| %>
                  <%= form.submit "Delete", class: "text-red-500 font-semibold" %>
                <% end %>
                <!-- <%= link_to "Delete", comment_path(comment),  class: "text-red-500 font-semibold", data: {turbo_method: :delete, 'turbo-confirm': 'Are you sure?', :id => comment.id } %> -->
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>

</div>

app/views/posts/user_posts.html.erb
<h1 class="text-center font-bold text-2xl">My Posts</h1>
  <% if user_signed_in? %>
    <%= link_to "Create new post", new_post_path, class: "btn btn-primary w-[200px]" %>
  <% end %>

  <ul class="flex flex-col gap-y-4">
  <%  @posts.each do | post | %>
    <% p = Post.find(post.id) %>
    <% comment_count = p.comments.all.count %>
    <div class="card bg-base-100 shadow-xl w-8/12 mx-auto">
      <div class="card-body">
        <h2 class="card-title"><%= post.title %></h2>
        <p><%= post.body %></p>
        <% if user_signed_in? %>
          <%= form_with model: Comment.new, url: "/comments", class: "mt-8 flex items-center",  method: :post do |form| %>
            <%= form.hidden_field :post_id, value: post.id %>
            <%= form.text_field :body, class: "border border-violet-500 rounded-md w-full mr-2" %>
            <%= form.button "Reply", class: "bg-violet-800 text-white py-2 px-6 rounded-md"%>
          <% end %>
        <% end %>
        <div class="mt-2 text-sm text-end text-gray-400">
          <p>By: <%= post.user.email %></p>
          <p>Diposting pada: <%= post.created_at %></p>
        </div>
        <div class="flex items-center justify-between mt-2">
          <% if comment_count > 0 %>
            <%= link_to "Cek komentar(#{comment_count})", post_path(post.id), class: "text-violet-700 font-semibold" %>
          <% end %>
          <div class="flex items-center space-x-2 ml-auto">
            <%= link_to "Update", edit_post_path(post), class: "text-violet-800 font-semibold" %>
            <%= form_with url: "/posts/#{post.id}", method: :delete, data: { turbo_confirm: 'Delete post?' } do |form| %>
              <%= form.submit "Delete", class: "text-red-500 font-semibold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </ul>